### ISSUE TITLE
Rendered elements after an array get repeated

### ISSUE THREAD

**Issue by matthewmueller** [ashaffer/virtex#1]
Hey there, just playing around with the example a bit. I noticed that any element after an array gets repeated:

```jsx
function app ({counters, list = []}) {
  return (
    <div>
      Hello World
      {
        counters.map((value, idx) => <Counter value={value} idx={idx} />)
      }
      <hr/> <!-- this will get turned into a counter -->
    </div>
  )
}
```

Here's what it'll end up looking like:

![](https://cldup.com/scVK5dV9Yg.png)

This gets resolved if you wrap the array in another element, but it's definitely than how react works

**Comment by ashaffer** [comment]
Ah, that could be a bug in the filterFlatten algorithm - definitely not intentional.  I'll get this fixed soon, i'm finishing up changes to the diff algorithm to make it, uh, actually work correctly as well.

**Comment by matthewmueller** [comment]
okay cool, i'll see if i can submit a patch

**Comment by ashaffer** [comment]
Just fixed this.  Turns out doing it right is faster too, which is neat.  I actually just spent the last 48 hours trying to fix a problem in the diff that I had only imagined, I think.

What is the re-rendering issue you're seeing?

**Comment by matthewmueller** [comment]
> Just fixed this. Turns out doing it right is faster too, which is neat.

Oh nice! Was planning on submitting something tonight, but you beat me to it haha. Looks like a better solution than I would have come up with anyway :-P

> I actually just spent the last 48 hours trying to fix a problem in the diff that I had only imagined, I think.

Dang.. so actually I might be mistaken that it's re-rendering, but it seems like it's performing a lot of extra tasks:

![img](https://cldup.com/z2ItgRNgIp.png)

This happens when I increment. It looks like it's removing and re-adding attributes every click. Could totally be how diffing works though. I haven't dug in at all.

**Comment by ashaffer** [comment]
The event handler re-rendering is actually expected.  It kind of sucks, but I think that's how it works in most virtual-dom's.  The fundamental problem is that since the event handler is defined in a closure, its value really is changing.  There are two ways to mitigate this though:

  1. Don't define the handlers inside your render.  
  2. Rely more on `shouldUpdate` to prevent re-rendering.  This isn't working in the case of the counter because it's data is actually changing.

That being said, [virtex-dom](https://github.com/ashaffer/virtex-dom) uses event delegation, so registering/deregistering event handlers is super cheap anyway.

**Comment by matthewmueller** [comment]
> The fundamental problem is that since the event handler is defined in a closure, its value really is changing each time render is called. There are two ways to mitigate this though:

Ahh yah, that makes sense. Thanks!

**Comment by ashaffer** [comment]
Ah nice. Will definitely use that in the future.
